[package]
name = "lightcryptotools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
mockall = "0.11.0"
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"

[[bin]]
path = "bin/randombytes.rs"
name = "randombytes"

